<script context="module">
    export const texts = [{
			id: 0,
			lang: "Français (FR)",
			h1: "Trouvez des objets 3D, des maquettes et des illustrations ici.",
			h2: "Créer un compte",
			btn_google: "Inscrivez-vous avec Google",
			btn_facebook: "Inscrivez-vous avec Facebook",
			or: "- OU -",
			sign_in: "Vous avez déjà un compte ?",
            sign_in_span: "Connectez vous",
            form_name: "Nom et prénom",
            form_mail: "Adresse e-mail",
            form_pwd: "Mot de passe",
            form_create: "Créer un compte",
		},
		{
			id: 1,
			lang: "English (GB)",
			h1: "Find 3D Objects, Mockups and Illustration here.",
			h2: "Create Account",
			btn_google: "Sign up with Google",
			btn_facebook: "Sign up with Facebook",
			or: "- OR -",
			sign_in: "Already have an account?",
            sign_in_span: "Log in",
            form_name: "Full Name",
            form_mail: "Email Address",
            form_pwd: "Password",
            form_create: "Create Account",
		},
		{
			id: 2,
			lang: "Español (SP)",
			h1: "Encuentre objetos 3D, maquetas e ilustraciones aquí.",
			h2: "Crear una cuenta",
			btn_google: "Registrarte con Google",
			btn_facebook: "Registrarte con Facebook",
			or: "- O -",
			sign_in: "¿Ya tienes una cuenta?",
            sign_in_span: "Acceso",
            form_name: "Nombre completo",
            form_mail: "Dirección de correo electrónico",
            form_pwd: "Contraseña",
            form_create: "Crear una cuenta",
		},
		{
			id: 3,
			lang: "Deutsch (DE)",
			h1: "Hier finden Sie 3D-Objekte, Modelle und Illustrationen.",
			h2: "Benutzerkonto erstellen",
			btn_google: "Anmelden mit Google",
			btn_facebook: "Anmelden mit Facebook",
			or: "- ODER -",
			sign_in: "Sie haben bereits ein Konto?",
            sign_in_span: "Anmeldung",
            form_name: "Vollständiger Name",
            form_mail: "E-Mail-Adresse",
            form_pwd: "Passwort",
            form_create: "Benutzerkonto erstellen",
		},
	];
</script>